---
title: Center Surround
author: ''
date: '2020-05-08'
slug: center-surround
categories: []
tags:
  - science around us
summary: ''
authors: []
external_link: ''
image:
  caption: 'Center Surround, by Jennifer Jahncke'
  focal_point: ''
  preview_only: no
url_code: ''
url_pdf: ''
url_slides: ''
url_video: ''
slides: ''
---

The back of your retina is lined with light-sensitive rods and cones. These photoreceptors catch the light and send the light information to bipolar cells, who then send it to retinal ganglion cells (RGCs). It's here, at the RGCs, that the chemical signal is turned into an electrical one that can be sent to the brain. First stop: the lateral geniculate nucleus (LGN) in the thalamus. The thalamus contains a whole slew of nuclei (collections of cells), each representing a different sense. (Example: the medial geniculate nucleus is for hearing.) The LGN then shoots the visual information up to primary visual cortex (V1) for basic processing. From V1 the information is sent to higher processing centers to extract more details about the visual scene and to form associations with previous memories.

Each step in the hierarchy deals with a more complicated concept. Spots of light becomes lines, which become curves, etc. But the receptive field of the RGC is worth noting. These cells are very particular about the stiumulus they need to see in order to fire. Here, you can see how a so-called "off-center" RGC receptive field looks. This cell will fire maximally when there is light illuminated only in the "surround" portion of the receptive field, with the center remaining in darkness.